import { StyleSheet, Text, useWindowDimensions, View } from 'react-native';

import { Card, Pill, SectionTitle } from '@/components/ui/operator-ui';
import { colors } from '@/constants/soilbot-theme';
import { useOperator } from '@/state/operator-context';
import type { Telemetry } from '@/types/soilbot';

function Chart({ title, unit, color, history, selector, min, max }: { title: string; unit: string; color: string; history: Telemetry[]; selector: (x: Telemetry) => number; min: number; max: number }) {
  const values = history.length > 1 ? history : [...history, ...Array.from({ length: 11 }, (_, i) => ({ ...history[0], timestamp: '', temperature: 27.8 + i * .08, airQuality: 39 + (i % 4), o2Level: 20.7 + (i % 3) * .08 }))];
  const current = selector(values[values.length - 1]);
  return <Card style={styles.chart}><SectionTitle aside={<Pill label="Live" tone="cyan" />}>{title}</SectionTitle><Text style={[styles.chartValue, { color }]}>{current.toFixed(1)}<Text style={styles.unit}> {unit}</Text></Text><View style={styles.bars}>{values.slice(-18).map((item, i) => { const height = Math.max(8, Math.min(100, ((selector(item) - min) / (max - min)) * 100)); return <View key={`${item.timestamp}-${i}`} style={[styles.bar, { height: `${height}%`, backgroundColor: i === values.length - 1 ? color : `${color}55` }]} />; })}</View><View style={styles.axis}><Text style={styles.axisText}>- 60 min</Text><Text style={styles.axisText}>Now</Text></View></Card>;
}

export function EnvironmentScreen() {
  const { width } = useWindowDimensions(); const { telemetry, history, position } = useOperator();
  return <View style={styles.page}><Card style={styles.location}><View><Text style={styles.kicker}>ACTIVE SAMPLE POSITION</Text><Text style={styles.locationTitle}>Row {position.gridY} · {position.gridX.toFixed(1)} metres</Text><Text style={styles.coords}>{position.latitude.toFixed(6)}, {position.longitude.toFixed(6)}</Text></View><View style={styles.quality}><Text style={styles.qualityLabel}>MICROCLIMATE</Text><Text style={styles.qualityValue}>{telemetry.airQuality < 50 ? 'Nominal' : 'Watch'}</Text></View></Card><View style={[styles.grid, width < 900 && styles.stack]}><Chart title="Ambient temperature" unit="°C" color={colors.amber} history={history} selector={(x) => x.temperature} min={15} max={40} /><Chart title="Air quality index" unit="AQI" color={colors.cyan} history={history} selector={(x) => x.airQuality} min={0} max={100} /><Chart title="Oxygen level" unit="% O₂" color={colors.green} history={history} selector={(x) => x.o2Level} min={18} max={23} /></View><Card><SectionTitle>Sensor guidance</SectionTitle><View style={styles.guidance}><Guide dot={colors.green} title="Oxygen normal" text="Expected outdoor range near 20.9%." /><Guide dot={colors.cyan} title="Air quality good" text="AQI remains below the 50 threshold." /><Guide dot={colors.amber} title="Heat watch" text="Monitor when ambient temperature exceeds 35°C." /></View></Card></View>;
}
function Guide({ dot, title, text }: { dot: string; title: string; text: string }) { return <View style={styles.guide}><View style={[styles.guideDot, { backgroundColor: dot }]} /><View><Text style={styles.guideTitle}>{title}</Text><Text style={styles.guideText}>{text}</Text></View></View>; }
const styles = StyleSheet.create({
  page: { gap: 18 }, location: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, kicker: { color: colors.green, fontSize: 9, letterSpacing: 1.4, fontWeight: '800' }, locationTitle: { color: colors.text, fontSize: 18, fontWeight: '800', marginTop: 5 }, coords: { color: colors.muted, fontSize: 11, marginTop: 4 }, quality: { alignItems: 'flex-end' }, qualityLabel: { color: colors.muted, fontSize: 9 }, qualityValue: { color: colors.green, fontSize: 17, fontWeight: '900', marginTop: 4 }, grid: { flexDirection: 'row', gap: 18 }, stack: { flexDirection: 'column' }, chart: { flex: 1, minHeight: 320 }, chartValue: { fontSize: 32, fontWeight: '900' }, unit: { color: colors.muted, fontSize: 12 }, bars: { height: 150, marginTop: 24, borderBottomWidth: 1, borderBottomColor: colors.border, flexDirection: 'row', gap: 4, alignItems: 'flex-end' }, bar: { flex: 1, minWidth: 3, borderTopLeftRadius: 3, borderTopRightRadius: 3 }, axis: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 }, axisText: { color: colors.muted, fontSize: 9 }, guidance: { flexDirection: 'row', flexWrap: 'wrap', gap: 20 }, guide: { minWidth: 210, flex: 1, flexDirection: 'row', gap: 10, alignItems: 'flex-start' }, guideDot: { width: 9, height: 9, borderRadius: 5, marginTop: 3 }, guideTitle: { color: colors.text, fontSize: 12, fontWeight: '800' }, guideText: { color: colors.muted, fontSize: 11, marginTop: 3 },
});
